name: check
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
  pull_request:
  pull_request_target:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    name: ${{ matrix.env }}${{ matrix.suffix || ''}}
    strategy:
      fail-fast: false
      matrix:
        env:
          - "3.14"
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - type
          - dev
          - pkg_meta
        os:
          - ubuntu-24.04
        suffix:
          - ""
        include:
          - env: "3.14"
            os: windows-2025
            suffix: -windows
          - env: "3.14"
            os: macos-15
            suffix: -macos
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install tox
        run: uv tool install --python-preference only-managed --python 3.14 tox --with .
      - name: Install Python
        if: startsWith(matrix.env, '3.') && matrix.env != '3.14'
        run: uv python install --python-preference only-managed ${{ matrix.env }}
      - name: Setup test suite
        run: tox run -vv --notest --skip-missing-interpreters false -e ${{ matrix.env }}
        env:
          FORCE_COLOR: "1"
          UV_PYTHON_PREFERENCE: "only-managed"
      - name: Run test suite
        run: tox run --skip-pkg-install -e ${{ matrix.env }}
        env:
          FORCE_COLOR: "1"
          PYTEST_ADDOPTS: "-vv --durations=20"
          DIFF_AGAINST: HEAD
          UV_PYTHON_PREFERENCE: "only-managed"
